---
- name: Deploy app to dev host
  hosts: all
  become_user: root

  vars:
      - destination: "/home/{{ ansible_user_id }}/api"
      - supervisord_program_name: "jetpack-api"

  tasks:
    - name: Ensure directories exist
      file:
        path: "{{ destination }}/log"
        state: directory

    - name: Copy app
      copy:
        src: build/libs/demo.jar
        dest: "{{ destination }}"

    - name: Generate & copy supervisord config
      template:
        src: supervisord.conf
        dest: "{{ destination }}"

    - name: Move supervisord config as superuser
      command: mv "{{ destination }}/supervisord.conf" "/etc/supervisord.d/{{ supervisord_program_name }}.ini"
      become: true

    - name: supervisorctl reread
      command: supervisorctl reread
      become: true

    - name: supervisorctl update
      command: supervisorctl update
      become: true

    - name: Restart app
      command: supervisorctl restart {{ supervisord_program_name }}
      become: true
